using System.Text;
using System.Text.Json;
using GeoCore.Data.Entities;

namespace GeoCore.SaaS.Services.GA4AITracking;

/// <summary>
/// GA4 AI 流量追踪配置服务
/// 功能 4.50：生成 GA4 AI 流量追踪配置，包括 LLM referrers 配置和 AI bot 识别
/// 数据来源：从 ConfigCacheService 缓存读取（数据库管理）
/// </summary>
public class GA4AITrackingService
{
    private readonly ILogger<GA4AITrackingService> _logger;
    private readonly ConfigCacheService _configCache;

    public GA4AITrackingService(
        ILogger<GA4AITrackingService> logger,
        ConfigCacheService configCache)
    {
        _logger = logger;
        _configCache = configCache;
    }

    /// <summary>
    /// 从缓存获取 AI 流量来源列表
    /// </summary>
    private List<AITrafficSource> GetAITrafficSourcesFromCache()
    {
        var referrers = _configCache.GetAllLLMReferrers();
        
        // 按平台名称分组，合并同一平台的多个 referrer
        var grouped = referrers
            .GroupBy(r => r.PlatformName)
            .Select(g => new AITrafficSource
            {
                Name = g.Key,
                Platform = g.First().Company ?? g.Key,
                ReferrerPatterns = g.Select(r => r.ReferrerPattern).ToList(),
                UserAgentPatterns = ParseJsonArray(g.First().UserAgentPatterns),
                TrafficType = g.First().TrafficType,
                EstimatedShare = g.Sum(r => r.EstimatedShare),
                Notes = g.First().Notes ?? ""
            })
            .OrderByDescending(s => s.EstimatedShare)
            .ToList();

        return grouped;
    }

    /// <summary>
    /// 解析 JSON 数组字符串
    /// </summary>
    private List<string> ParseJsonArray(string? json)
    {
        if (string.IsNullOrEmpty(json)) return new List<string>();
        try
        {
            return JsonSerializer.Deserialize<List<string>>(json) ?? new List<string>();
        }
        catch
        {
            return new List<string>();
        }
    }

    /// <summary>
    /// 生成 GA4 AI 流量追踪配置
    /// </summary>
    public GA4AITrackingConfigResult GenerateConfig(GA4AITrackingConfigRequest request)
    {
        _logger.LogInformation("[GA4AITracking] Generating config for {Url}", request.WebsiteUrl);

        // 从缓存获取 AI 流量来源
        var aiTrafficSources = GetAITrafficSourcesFromCache();

        var result = new GA4AITrackingConfigResult
        {
            GeneratedAt = DateTime.UtcNow,
            TrafficSources = aiTrafficSources
        };

        // 生成渠道分组配置
        result.ChannelGroupConfig = GenerateChannelGroupConfig();

        // 生成自定义事件代码
        if (request.IncludeCustomEvents)
        {
            result.CustomEventCode = GenerateCustomEventCode(request.MeasurementId);
        }

        // 生成 GTM 配置
        if (request.IncludeGTMConfig)
        {
            result.GTMConfigJson = GenerateGTMConfig();
        }

        // 生成实施步骤
        result.ImplementationSteps = GenerateImplementationSteps(request);

        // 生成推荐报告
        result.RecommendedReports = GenerateRecommendedReports();

        _logger.LogInformation("[GA4AITracking] Config generated with {SourceCount} traffic sources",
            result.TrafficSources.Count);

        return result;
    }

    /// <summary>
    /// 生成渠道分组配置
    /// </summary>
    private GA4ChannelGroupConfig GenerateChannelGroupConfig()
    {
        var config = new GA4ChannelGroupConfig
        {
            GroupName = "AI Traffic",
            ConfigurationInstructions = @"在 GA4 Admin 中配置自定义渠道分组：
1. 进入 Admin > Data display > Channel groups
2. 点击 'Create new channel group'
3. 命名为 'AI Traffic'
4. 添加以下规则（按优先级顺序）"
        };

        // 从缓存获取 AI 流量来源
        var aiTrafficSources = GetAITrafficSourcesFromCache();

        var priority = 1;
        foreach (var source in aiTrafficSources)
        {
            foreach (var pattern in source.ReferrerPatterns)
            {
                config.Rules.Add(new ChannelRule
                {
                    Name = $"AI - {source.Name}",
                    ConditionType = "source",
                    MatchType = "contains",
                    MatchValue = pattern,
                    Priority = priority++
                });
            }
        }

        return config;
    }

    /// <summary>
    /// 生成自定义事件代码
    /// </summary>
    private string GenerateCustomEventCode(string? measurementId)
    {
        var mid = measurementId ?? "G-XXXXXXXXXX";

        return $@"<!-- GA4 AI Traffic Tracking - Generated by GeoCore AI -->
<script>
// AI 流量来源检测和追踪
(function() {{
  'use strict';
  
  // AI 平台 referrer 模式
  const AI_REFERRERS = [
    {{ name: 'ChatGPT', patterns: ['chat.openai.com', 'chatgpt.com', 'openai.com'] }},
    {{ name: 'Perplexity', patterns: ['perplexity.ai'] }},
    {{ name: 'Claude', patterns: ['claude.ai', 'anthropic.com'] }},
    {{ name: 'Google AI', patterns: ['gemini.google.com', 'bard.google.com', 'ai.google'] }},
    {{ name: 'Copilot', patterns: ['copilot.microsoft.com', 'bing.com/chat'] }},
    {{ name: 'You.com', patterns: ['you.com'] }},
    {{ name: 'Phind', patterns: ['phind.com'] }},
    {{ name: 'Kagi', patterns: ['kagi.com'] }}
  ];
  
  // 检测 AI 流量来源
  function detectAISource() {{
    const referrer = document.referrer.toLowerCase();
    if (!referrer) return null;
    
    for (const source of AI_REFERRERS) {{
      for (const pattern of source.patterns) {{
        if (referrer.includes(pattern)) {{
          return source.name;
        }}
      }}
    }}
    return null;
  }}
  
  // 发送 AI 流量事件
  function trackAITraffic() {{
    const aiSource = detectAISource();
    if (aiSource) {{
      // 使用 gtag 发送自定义事件
      if (typeof gtag === 'function') {{
        gtag('event', 'ai_traffic', {{
          'ai_source': aiSource,
          'referrer': document.referrer,
          'landing_page': window.location.pathname,
          'timestamp': new Date().toISOString()
        }});
        
        // 设置用户属性
        gtag('set', 'user_properties', {{
          'ai_referred': 'true',
          'ai_source': aiSource
        }});
        
        console.log('[GA4 AI Tracking] Detected AI traffic from:', aiSource);
      }}
    }}
  }}
  
  // 页面加载时执行
  if (document.readyState === 'loading') {{
    document.addEventListener('DOMContentLoaded', trackAITraffic);
  }} else {{
    trackAITraffic();
  }}
}})();
</script>

<!-- GA4 基础配置（如果尚未添加） -->
<script async src=""https://www.googletagmanager.com/gtag/js?id={mid}""></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){{dataLayer.push(arguments);}}
  gtag('js', new Date());
  gtag('config', '{mid}');
</script>";
    }

    /// <summary>
    /// 生成 GTM 配置
    /// </summary>
    private string GenerateGTMConfig()
    {
        var gtmConfig = new
        {
            exportFormatVersion = 2,
            containerVersion = new
            {
                tag = new[]
                {
                    new
                    {
                        name = "AI Traffic Detection",
                        type = "html",
                        parameter = new[]
                        {
                            new { key = "html", value = GetGTMCustomHtml() }
                        },
                        firingTriggerId = new[] { "2147479553" },
                        tagFiringOption = "oncePerPage"
                    }
                },
                trigger = new[]
                {
                    new
                    {
                        triggerId = "2147479553",
                        name = "All Pages",
                        type = "pageview"
                    }
                },
                variable = new[]
                {
                    new
                    {
                        name = "AI Source",
                        type = "jsm",
                        parameter = new[]
                        {
                            new { key = "javascript", value = GetAISourceDetectionJS() }
                        }
                    }
                }
            }
        };

        return JsonSerializer.Serialize(gtmConfig, new JsonSerializerOptions { WriteIndented = true });
    }

    private string GetGTMCustomHtml()
    {
        return @"<script>
(function() {
  var aiSource = {{AI Source}};
  if (aiSource) {
    dataLayer.push({
      'event': 'ai_traffic',
      'ai_source': aiSource,
      'referrer': document.referrer
    });
  }
})();
</script>";
    }

    private string GetAISourceDetectionJS()
    {
        return @"function() {
  var referrer = document.referrer.toLowerCase();
  var sources = {
    'chat.openai.com': 'ChatGPT',
    'chatgpt.com': 'ChatGPT',
    'perplexity.ai': 'Perplexity',
    'claude.ai': 'Claude',
    'gemini.google.com': 'Google AI',
    'copilot.microsoft.com': 'Copilot'
  };
  for (var pattern in sources) {
    if (referrer.indexOf(pattern) !== -1) {
      return sources[pattern];
    }
  }
  return null;
}";
    }

    /// <summary>
    /// 生成实施步骤
    /// </summary>
    private List<ImplementationStep> GenerateImplementationSteps(GA4AITrackingConfigRequest request)
    {
        var steps = new List<ImplementationStep>
        {
            new ImplementationStep
            {
                StepNumber = 1,
                Title = "创建 GA4 自定义渠道分组",
                Description = "在 GA4 Admin 中创建 'AI Traffic' 渠道分组",
                Actions = new List<string>
                {
                    "登录 Google Analytics 4",
                    "进入 Admin > Data display > Channel groups",
                    "点击 'Create new channel group'",
                    "命名为 'AI Traffic'",
                    "添加规则：Source contains 'chat.openai.com' → AI - ChatGPT",
                    "添加规则：Source contains 'perplexity.ai' → AI - Perplexity",
                    "添加规则：Source contains 'claude.ai' → AI - Claude",
                    "保存渠道分组"
                },
                EstimatedMinutes = 15
            },
            new ImplementationStep
            {
                StepNumber = 2,
                Title = "添加 AI 流量追踪代码",
                Description = "将 AI 流量检测代码添加到网站",
                Actions = new List<string>
                {
                    "复制上方的自定义事件代码",
                    "将代码添加到网站的 <head> 标签中",
                    "或通过 GTM 添加自定义 HTML 标签",
                    "确保代码在 GA4 基础代码之后加载"
                },
                CodeSnippet = "参见上方 CustomEventCode",
                EstimatedMinutes = 10
            },
            new ImplementationStep
            {
                StepNumber = 3,
                Title = "创建自定义事件",
                Description = "在 GA4 中注册 ai_traffic 自定义事件",
                Actions = new List<string>
                {
                    "进入 Admin > Events",
                    "点击 'Create event'",
                    "事件名称：ai_traffic",
                    "添加参数：ai_source, referrer, landing_page",
                    "保存事件"
                },
                EstimatedMinutes = 5
            },
            new ImplementationStep
            {
                StepNumber = 4,
                Title = "创建自定义维度",
                Description = "创建 AI 来源自定义维度用于报告",
                Actions = new List<string>
                {
                    "进入 Admin > Custom definitions > Custom dimensions",
                    "点击 'Create custom dimension'",
                    "维度名称：AI Source",
                    "范围：Event",
                    "事件参数：ai_source",
                    "保存维度"
                },
                EstimatedMinutes = 5
            },
            new ImplementationStep
            {
                StepNumber = 5,
                Title = "创建 AI 流量报告",
                Description = "创建专门的 AI 流量分析报告",
                Actions = new List<string>
                {
                    "进入 Explore > Create new exploration",
                    "添加维度：AI Source, Landing page",
                    "添加指标：Sessions, Users, Conversions",
                    "设置过滤器：Event name = ai_traffic",
                    "保存报告"
                },
                EstimatedMinutes = 10
            },
            new ImplementationStep
            {
                StepNumber = 6,
                Title = "设置告警（可选）",
                Description = "设置 AI 流量变化告警",
                Actions = new List<string>
                {
                    "进入 Admin > Custom alerts",
                    "创建新告警：AI Traffic Spike",
                    "条件：ai_traffic 事件数 > 阈值",
                    "设置通知方式（邮件/Slack）"
                },
                EstimatedMinutes = 5
            }
        };

        return steps;
    }

    /// <summary>
    /// 生成推荐报告
    /// </summary>
    private List<RecommendedReport> GenerateRecommendedReports()
    {
        return new List<RecommendedReport>
        {
            new RecommendedReport
            {
                Name = "AI 流量概览",
                Description = "按 AI 平台分析流量来源和用户行为",
                ReportType = "exploration",
                Dimensions = new List<string> { "AI Source", "Landing page", "Device category" },
                Metrics = new List<string> { "Sessions", "Users", "Engagement rate", "Conversions" },
                CreationInstructions = "使用 Free-form exploration，按 AI Source 分组"
            },
            new RecommendedReport
            {
                Name = "AI vs 传统流量对比",
                Description = "对比 AI 流量和传统搜索流量的转化效果",
                ReportType = "exploration",
                Dimensions = new List<string> { "Session default channel group", "AI Source" },
                Metrics = new List<string> { "Sessions", "Conversion rate", "Revenue" },
                CreationInstructions = "使用 Cohort exploration 对比不同来源"
            },
            new RecommendedReport
            {
                Name = "AI 流量着陆页分析",
                Description = "分析哪些页面最常被 AI 平台引用",
                ReportType = "exploration",
                Dimensions = new List<string> { "Landing page", "AI Source" },
                Metrics = new List<string> { "Sessions", "Bounce rate", "Pages per session" },
                CreationInstructions = "按 Landing page 排序，筛选 AI 流量"
            },
            new RecommendedReport
            {
                Name = "AI 流量趋势",
                Description = "追踪 AI 流量随时间的变化趋势",
                ReportType = "exploration",
                Dimensions = new List<string> { "Date", "AI Source" },
                Metrics = new List<string> { "Sessions", "Users" },
                CreationInstructions = "使用 Line chart 展示趋势，按日/周分组"
            }
        };
    }

    /// <summary>
    /// 获取所有 AI 流量来源定义（从缓存读取）
    /// </summary>
    public List<AITrafficSource> GetAITrafficSources()
    {
        return GetAITrafficSourcesFromCache();
    }
}
